### ISSUE TITLE
ns_guestbook mailing issue

### ISSUE THREAD

**Issue by georgmarius** [nitsan-technologies/ns_guestbook#1]
Hello  
I just installed the ns_guestbook extension and followed the installation instructions and things  fine until I try it out and ran into  a mailing issue: 
On submitting the form i get the following Error message:  

`Address in mailbox given [mailto:testmail@test.com] does not comply with RFC 2822, 3.6.2.`

And the protokollmessage is:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Address in mailbox given [mailto:testmail@test.com] does not comply with RFC 2822, 3.6.2. | Swift_RfcComplianceException thrown in file /var/www/html/typo3_src-9.5.5/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php in line 345
` 
(in this message I replaced my actually email with "testmail@test.com" but the formatting is the same )
I am using Typo3 9.5.5 and typo3 mail handling setting are set to smtp.
Mailing from our typo3 system usually works fine and the system test mail is working too.
Im wondering if the "mailto:" part should actually be there.

Hope you can help
Best regards,
Georg Marius

**Comment by nitsan-technologies** [comment]
Hey there 

It could be a server configuration issue or an issue with your email address. Please let us know if this issue persists.
