### ISSUE TITLE
Oops, an error occurred!

### ISSUE THREAD

**Issue by nitsan-technologies** [nitsan-technologies/ns_guestbook#15]
I'm currently trying to activate the ns_guestbook plugin on a website. Even though I believe I've configured everything according to the documentation, and I've also entered the Google reCAPTCHA site and secret keys in the constants, I receive an error message when trying to submit a guestbook entry: "Oops, an error occurred! Code: 2023110116555633bd1b3d."

**Comment by nitsan-technologies** [comment]
The issue has been resolved and it will be included in the upcoming release.

**Comment by stpink** [comment]
Thank you very.

Is the new release of the guestbook already available?
What is the URL where it can be accessed?
Maybe in the TYPO3-TER?

**Comment by nilesh-nitsan** [comment]
Hi @stpink 
Thanks for using our extension and giving us valuable feedback. You can download the latest released extension from here -  https://extensions.typo3.org/extension/download/ns_guestbook/3.2.3/zip

Thanks 🙏 
Nilesh @nitsan-technologies

**Comment by stpink** [comment]
Thank you very mich for the download-link.
But this is the old version for TYPO3 version 11
I meant the aktual new version higher than 12.0.0 for typo3-version 12

Greetings
stefan

**Comment by nitsan-technologies** [comment]
Hey @stpink  

Can you please add **_config.contentObjectExceptionHandler = 0_** to your TypoScript(![image](https://github.com/nitsan-technologies/ns_guestbook/assets/2622317/60e10d4a-7822-4a40-95ec-09e58d605135)) and again submit the form and share screenshot of an issue, It will help me to understand your issue.

**Comment by stpink** [comment]
I would like to revisit the issue with ns_guestbook.

In Typo3 version 11, it works perfectly with ns_guestbook 3.2.3.
However, in Typo3 version 12.4.x and ns_guestbook 12.0.0, there are problems with the form.
When trying to send, an error message appears [Oops, an error occurred! Code: 20231129133440d6b318ae].
No email is sent to the admin.

Both installations use the Bootstrap extension t3sbootstrap.

Thank you for your feedback.
Stefan
