### ISSUE TITLE
Missing option for data privacy agreement DSGVO checkbox

### ISSUE THREAD

**Issue by georgmarius** [nitsan-technologies/ns_guestbook#2]
Hello. 
In the EU we now need a mandatory checkbox to confirm the data privacy agreement, but this Guestbook extension das not have such a field. Could you please add such a field to the next update or provide a guide on how to extend this extension(tried it my self but so far with no success).
Best regards
Georg Marius

**Comment by nitsan-technologies** [comment]
Hello @georgmarius 
Greetings of the day!

FYI, We have added the field as you have mentioned. Please download/update with the latest version of the extension.

Thanks!
Team NITSAN
