### ISSUE TITLE
Captcha disabled but still connection to Google, GDPR issue

### ISSUE THREAD

**Issue by medarob** [nitsan-technologies/ns_guestbook#7]
Hi,

I disabled the Captcha Option:
![grafik](https://user-images.githubusercontent.com/33951787/88038670-d6cb0500-cb46-11ea-97ae-9ceaebd28d00.png)

But, I noticed in the console that there is still a connection to
![grafik](https://user-images.githubusercontent.com/33951787/88038026-f44b9f00-cb45-11ea-8511-d15220adb170.png)
and
![grafik](https://user-images.githubusercontent.com/33951787/88038081-07f70580-cb46-11ea-8f57-cdf2b30be84c.png)

What I expect to happen is, that when I disable the Captcha option that no connection to any external service is established. Otherwise it's not GDPR compliant. The user has to give consent to any external service.

Maybe this is related to the following issue:
After I clicked on the submit button it takes ~40-50 sec until the feedback is stored and the pages reloads. That can't be correct. Maybe that is the case because it tries to load external services?

TYPO3 9.5.19 and Guestbook v 2.1

**Comment by medarob** [comment]
I added this Typoscript to my own setup and now the api.js is not called.

```
page {
	includeJS {
		//1000 = https://www.google.com/recaptcha/api.js
		//1000.external = 1
		1000.if.isTrue = {$plugin.tx_nsguestbook_form.settings.sitekey}
	}
}
```

Not sure if that is the best solution because it depends on the constants settings for the api key. But it works. No api key, no integration of the file via Typosrcipt. The setting in the form BE where I can disable the Captcha seems to be not used?

This does not seems to solve the long loading time - so it seems to be another issue.
![grafik](https://user-images.githubusercontent.com/33951787/88049833-13522d00-cb56-11ea-8f4a-01b254e63f05.png)

**Comment by nitsan-technologies** [comment]
Hello There
Greetings of the day!

Thanks for pointing out the issue, FYI, We have resolved the issue. Please download the latest version of this extension.

Thanks!
Team NITSAN
